import React from 'react';
import { PageTransition } from '../components/PageTransition';
import { Hero } from '../components/Hero';
import { WhatAssociumDoesSection } from '../components/WhatAssociumDoesSection';
import { IntegrationsSection } from '../components/IntegrationsSection';
import { HowItWorksSection } from '../components/HowItWorksSection';
import { SampleOutputsSection } from '../components/SampleOutputsSection';
import { IndustrySection } from '../components/IndustrySection';
import { DifferenceSection } from '../components/DifferenceSection';
import { SecuritySection } from '../components/SecuritySection';
import { PricingIntroSection } from '../components/PricingIntroSection';
import { PricingCtaSection } from '../components/PricingCtaSection';

import { SEO } from '../components/SEO';

export function HomePage() {
  return (
    <PageTransition>
      <SEO 
        title="Associum: Your AI Associate for Professional Work"
        description="Associum completes the full professional production cycle — data, research, analysis, and finished document — for finance, consulting, accounting, and legal professionals. Done, not drafted. Sign-off ready."
        ogTitle="Associum — Your AI Associate for Professional Work"
        ogDescription="Associum completes the full professional production cycle — data, research, analysis, and finished document — for finance, consulting, accounting, and legal professionals. Done, not drafted. Sign-off ready."
        ogImage="/associo-og-home.jpg"
        ogImageAlt="Investment committee memo generated by Associum from raw financial data — near-final, sourced, and sign-off ready"
      />
      <Hero />
      <main>
        <WhatAssociumDoesSection />
        <IntegrationsSection />
        <HowItWorksSection />
        <SampleOutputsSection />
        <IndustrySection />
        <DifferenceSection />
        <SecuritySection />
        {/* <PricingIntroSection /> */}
        <PricingCtaSection />
      </main>
    </PageTransition>
  );
}
